name: needs port upstream
on:
  repository_dispatch:
    types: [port-upstream]
permissions:
  issues: write
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: create issue
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            github.rest.issues.create({
              owner: 'nuxt',
              repo: 'bridge',
              title: 'Need to port from upstream',
              labels: ['upstream'],
              body: `Upstream has been changed.
              Please check the changes and port them.

              ## Pull Request
              - ${{github.event.client_payload.url}}`,
            })
